#!/usr/bin/env bash
# Shared library for orchestrator-compose integration tests.
# Source from each test script; provides setup/teardown helpers.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.test.yml"
TESTDATA_DIR="${SCRIPT_DIR}/testdata"

# Detect docker-compose v1 or v2 (plugin). Mirrors the dispatch pattern
# already used in infra/scripts/run.sh.
if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  echo "FATAL: neither 'docker compose' nor 'docker-compose' is installed" >&2
  exit 1
fi

ensure_testdata() {
  mkdir -p "${TESTDATA_DIR}/proj/.github"
  if [[ ! -f "${TESTDATA_DIR}/proj/.github/runner.yml" ]]; then
    cat > "${TESTDATA_DIR}/proj/.github/runner.yml" <<'EOF'
runtime: node:24
labels: [self-hosted, Linux, container]
resources:
  memory: 4g
  cpus: 2
  pids: 1024
egress:
  allow_domains: [api.github.com]
orchestrator:
  timeout_seconds: 60
EOF
  fi
  if [[ ! -f "${TESTDATA_DIR}/scope.yml" ]]; then
    cat > "${TESTDATA_DIR}/scope.yml" <<'EOF'
apiVersion: runsecure.io/v1alpha1
name: test
global_max_runners: 3
poll_interval_seconds: 5
security_profile: strict
auth:
  type: pat
  pat_file: /run/secrets/runsecure-pat
orch_egress:
  allow_domains: [api.github.com]
repos:
  - repo: owner/repo
    project_dir: /projects/proj
    max_concurrent: 2
EOF
  fi
  if [[ ! -f "${TESTDATA_DIR}/pat" ]]; then
    echo "ghp_fake_for_tests" > "${TESTDATA_DIR}/pat"
    chmod 400 "${TESTDATA_DIR}/pat"
  fi
  # Bug #5 fix: generate a test allowed-images.txt so socket-proxy will
  # accept spawns of a real test-runner image.
  ensure_test_allowlist
}

# build_test_runner_image creates a minimal alpine-based image that the
# integration tests use in place of a real actions/runner. It exposes the
# networking tools we need to probe structural-floor properties from
# inside a spawned runner container.
build_test_runner_image() {
  if docker image inspect runsecure-test-runner:local >/dev/null 2>&1; then
    return 0
  fi
  local builddir
  builddir=$(mktemp -d)
  cat > "${builddir}/Dockerfile" <<'EOF'
FROM alpine:3.20
RUN apk add --no-cache curl bind-tools iproute2 netcat-openbsd
USER 1001:0
ENTRYPOINT ["sleep", "120"]
EOF
  docker build -t runsecure-test-runner:local "$builddir" >/dev/null
  rm -rf "$builddir"
}

# ensure_test_allowlist resolves the digest (or ID fallback) of the local
# test-runner image and writes a single-entry allowed-images.txt that the
# compose stack will bind-mount over the socket-proxy's baked-in empty file.
#
# Exports RUNSECURE_TEST_RUNNER_REF as the full ref the orchestrator will
# pass to socket-proxy's containers/create — must match the allowlist entry
# byte-for-byte.
#
# If RUNSECURE_TEST_OVERRIDE_ALLOWLIST is set, the file is NOT overwritten
# (the caller has set up a deliberately-empty allowlist for the
# leak-cleanup test). The env-var export still happens so the orchestrator
# tries to spawn (and gets refused by the empty allowlist).
ensure_test_allowlist() {
  build_test_runner_image
  local id
  id=$(docker image inspect runsecure-test-runner:local --format '{{.Id}}')
  local ref="runsecure-test-runner:local@${id}"
  if [[ -z "${RUNSECURE_TEST_OVERRIDE_ALLOWLIST:-}" ]]; then
    cat > "${TESTDATA_DIR}/allowed-images.txt" <<EOF
# Test allowlist generated by _lib.sh.
${ref}
EOF
  fi
  export RUNSECURE_TEST_RUNNER_REF="${ref}"
  export RUNSECURE_TEST_PROXY_REF="${ref}"
}

# project_name returns a unique compose project name based on this script.
project_name() {
  echo "rs-test-$(basename "$0" .sh)"
}

stack_up() {
  local pname; pname="$(project_name)"
  ensure_testdata
  $DC -f "${COMPOSE_FILE}" -p "${pname}" up -d --build mock-github socket-proxy orchestrator
}

stack_down() {
  local pname; pname="$(project_name)"
  $DC -f "${COMPOSE_FILE}" -p "${pname}" down --volumes --remove-orphans 2>/dev/null || true
  # Spawn-sibling containers live OUTSIDE the compose project — reap by label.
  docker ps -a --filter "label=runsecure.scope=test" --format '{{.ID}}' \
    | xargs -r docker rm -f >/dev/null 2>&1 || true
  docker network ls --filter "name=rs-net-" --format '{{.ID}}' \
    | xargs -r docker network rm >/dev/null 2>&1 || true
}

orch_logs() {
  local pname; pname="$(project_name)"
  $DC -f "${COMPOSE_FILE}" -p "${pname}" logs orchestrator 2>&1
}

# wait_for_log <pattern> [timeout_seconds]
wait_for_log() {
  local pat="$1"; local timeout="${2:-30}"
  local elapsed=0
  while (( elapsed < timeout )); do
    if orch_logs | grep -q "${pat}"; then
      return 0
    fi
    sleep 1
    elapsed=$((elapsed + 1))
  done
  echo "wait_for_log: never saw pattern: ${pat}" >&2
  orch_logs | tail -50 >&2
  return 1
}
