#!/bin/bash
# ============================================================================
# RunSecure — Image Composer
# ============================================================================
# Reads a project's runner.yml and builds a project-specific Docker image
# by layering tool recipes on top of the appropriate language base image.
#
# The resulting image is tagged with a hash of the configuration so that
# identical configs across projects share the same image (deduplication).
#
# Usage:
#   ./infra/scripts/compose-image.sh /path/to/project
#   ./infra/scripts/compose-image.sh /path/to/project --force  # rebuild
#
# Requires:
#   - Docker
#   - yq (YAML parser) — brew install yq
#   - runner-base image built
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNSECURE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TOOLS_DIR="${RUNSECURE_ROOT}/tools"
IMAGES_DIR="${RUNSECURE_ROOT}/images"

# --- Arguments ---------------------------------------------------------------
PROJECT_DIR="${1:?Usage: compose-image.sh /path/to/project [--force]}"
FORCE_REBUILD="${2:-}"

if [[ ! -d "$PROJECT_DIR" ]]; then
    echo "[RunSecure] ERROR: Project directory not found: $PROJECT_DIR"
    exit 1
fi

RUNNER_YML="${PROJECT_DIR}/.github/runner.yml"
if [[ ! -f "$RUNNER_YML" ]]; then
    echo "[RunSecure] ERROR: No .github/runner.yml found in $PROJECT_DIR"
    exit 1
fi

# --- Parse runner.yml --------------------------------------------------------
echo "[RunSecure] Reading config: $RUNNER_YML"

RUNTIME=$(yq '.runtime' "$RUNNER_YML")
TOOLS=$(yq '.tools // [] | .[]' "$RUNNER_YML" 2>/dev/null || true)
APT_PACKAGES=$(yq '.apt // [] | .[]' "$RUNNER_YML" 2>/dev/null || true)
MEMORY=$(yq '.resources.memory // "6g"' "$RUNNER_YML")
CPUS=$(yq '.resources.cpus // "4"' "$RUNNER_YML")
PIDS=$(yq '.resources.pids // "1024"' "$RUNNER_YML")
WORKSPACE=$(yq '.resources.workspace // "12g"' "$RUNNER_YML")

# Parse runtime into language and version
LANG=$(echo "$RUNTIME" | cut -d: -f1)
VERSION=$(echo "$RUNTIME" | cut -d: -f2)

echo "[RunSecure] Runtime: $LANG:$VERSION"
echo "[RunSecure] Tools: ${TOOLS:-none}"

# --- Ensure base image exists ------------------------------------------------
if ! docker image inspect "runner-base:latest" &>/dev/null; then
    echo "[RunSecure] Building runner-base..."
    docker build -f "${IMAGES_DIR}/base.Dockerfile" -t runner-base:latest "${RUNSECURE_ROOT}"
fi

# --- Ensure language image exists --------------------------------------------
LANG_IMAGE="runner-${LANG}:${VERSION}"
LANG_DOCKERFILE="${IMAGES_DIR}/${LANG}.Dockerfile"

if [[ ! -f "$LANG_DOCKERFILE" ]]; then
    echo "[RunSecure] ERROR: No Dockerfile for language '$LANG' at $LANG_DOCKERFILE"
    exit 1
fi

if ! docker image inspect "$LANG_IMAGE" &>/dev/null; then
    echo "[RunSecure] Building $LANG_IMAGE..."

    case "$LANG" in
        node)   BUILD_ARG="NODE_VERSION=${VERSION}" ;;
        python) BUILD_ARG="PYTHON_VERSION=${VERSION}" ;;
        rust)   BUILD_ARG="RUST_VERSION=${VERSION}" ;;
        *)      BUILD_ARG="" ;;
    esac

    docker build \
        -f "$LANG_DOCKERFILE" \
        --build-arg "BASE_TAG=latest" \
        ${BUILD_ARG:+--build-arg "$BUILD_ARG"} \
        -t "$LANG_IMAGE" \
        "${RUNSECURE_ROOT}"
fi

# --- Generate project-specific Dockerfile ------------------------------------
# If no tools and no extra apt packages, use the language image directly.
if [[ -z "$TOOLS" && -z "$APT_PACKAGES" ]]; then
    echo "[RunSecure] No tools or extra packages — using $LANG_IMAGE directly."
    echo "$LANG_IMAGE"
    exit 0
fi

# Create a deterministic hash of the config to tag the image
CONFIG_HASH=$(echo "${RUNTIME}|${TOOLS}|${APT_PACKAGES}" | sha256sum | cut -c1-12)
PROJECT_IMAGE="runner-project:${CONFIG_HASH}"

# Check if image already exists (skip rebuild unless --force)
if docker image inspect "$PROJECT_IMAGE" &>/dev/null && [[ "$FORCE_REBUILD" != "--force" ]]; then
    echo "[RunSecure] Image $PROJECT_IMAGE already exists (cached)."
    echo "$PROJECT_IMAGE"
    exit 0
fi

echo "[RunSecure] Composing project image: $PROJECT_IMAGE"

# Build a temporary Dockerfile
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

DOCKERFILE="${TMPDIR}/Dockerfile"

cat > "$DOCKERFILE" <<HEADER
# Auto-generated by RunSecure compose-image.sh
# Config hash: ${CONFIG_HASH}
FROM ${LANG_IMAGE}

USER root
HEADER

# Add extra apt packages if specified
if [[ -n "$APT_PACKAGES" ]]; then
    echo "" >> "$DOCKERFILE"
    echo "# --- Extra system packages from runner.yml ---" >> "$DOCKERFILE"
    echo "RUN apt-get update 2>/dev/null || true \\" >> "$DOCKERFILE"
    echo "    && apt-get install -y --no-install-recommends \\" >> "$DOCKERFILE"
    while IFS= read -r pkg; do
        echo "         ${pkg} \\" >> "$DOCKERFILE"
    done <<< "$APT_PACKAGES"
    echo "    && rm -rf /var/lib/apt/lists/*" >> "$DOCKERFILE"
fi

# Add tool recipes
if [[ -n "$TOOLS" ]]; then
    while IFS= read -r tool; do
        RECIPE="${TOOLS_DIR}/${tool}.sh"
        if [[ ! -f "$RECIPE" ]]; then
            echo "[RunSecure] WARNING: No recipe for tool '$tool' at $RECIPE — skipping."
            continue
        fi
        echo "" >> "$DOCKERFILE"
        echo "# --- Tool: ${tool} (from tools/${tool}.sh) ---" >> "$DOCKERFILE"
        echo "COPY tools/${tool}.sh /tmp/install-${tool}.sh" >> "$DOCKERFILE"
        echo "RUN chmod +x /tmp/install-${tool}.sh && /tmp/install-${tool}.sh && rm /tmp/install-${tool}.sh" >> "$DOCKERFILE"
    done <<< "$TOOLS"
fi

# Re-apply hardening and switch back to runner user
cat >> "$DOCKERFILE" <<FOOTER

# --- Re-apply hardening after tool installation ---
RUN rm -rf /usr/bin/apt* /usr/bin/dpkg* /usr/lib/apt /usr/lib/dpkg \
           /var/lib/apt /var/lib/dpkg /var/cache/apt /etc/apt \
    2>/dev/null || true \\
    && find / -perm /6000 -type f -exec chmod a-s {} + 2>/dev/null || true \\
    && chmod 444 /etc/passwd /etc/group 2>/dev/null || true \\
    && chmod 555 /etc 2>/dev/null || true

USER runner
WORKDIR /home/runner
FOOTER

echo "[RunSecure] Generated Dockerfile:"
cat "$DOCKERFILE"
echo ""

# Build the project image (using RunSecure root as context for tool scripts)
docker build \
    -f "$DOCKERFILE" \
    -t "$PROJECT_IMAGE" \
    "${RUNSECURE_ROOT}"

echo "[RunSecure] Built: $PROJECT_IMAGE"
echo "$PROJECT_IMAGE"
