#!/bin/bash
# ============================================================================
# RunSecure — Finalize Image Hardening
# ============================================================================
# Called as the LAST step in the final runnable image (via compose-image.sh).
# Removes the package manager, re-strips setuid binaries, and locks /etc.
#
# This is separated from base.Dockerfile because language layers and tool
# recipes need apt during image build. Only the final image strips it.
# ============================================================================

set -euo pipefail

echo "[RunSecure] Finalizing image hardening..."

# M10: every operation below was previously suffixed with `2>/dev/null
# || true`, which converted any failure (read-only filesystem, missing
# binary path, immutable bit set) into a silent success — the script
# would then claim "Hardening finalized" without having actually done
# anything. With set -euo pipefail and the masks removed, an unexpected
# failure now aborts the image build instead of producing a degraded
# image that the operator believes is hardened.

# Remove package manager so nothing can be installed at runtime.
# rm -rf with -f returns 0 for non-existent paths, so this is safe to
# run even on images where apt was already stripped earlier.
rm -rf \
    /usr/bin/apt /usr/bin/apt-get /usr/bin/apt-cache /usr/bin/apt-config \
    /usr/bin/apt-key /usr/bin/apt-mark /usr/bin/aptitude \
    /usr/bin/dpkg /usr/bin/dpkg-deb /usr/bin/dpkg-divert /usr/bin/dpkg-query \
    /usr/bin/dpkg-split /usr/bin/dpkg-statoverride /usr/bin/dpkg-trigger \
    /usr/lib/apt \
    /usr/lib/dpkg \
    /var/lib/apt \
    /var/lib/dpkg \
    /var/cache/apt \
    /etc/apt

# Re-strip setuid/setgid bits added by any tool install. Use -print0 |
# xargs -0 -r so an unreadable filesystem entry on `find`'s walk does
# NOT mask a chmod failure on a real binary (which is what we care
# about). xargs propagates chmod's exit code.
find / -xdev -perm /6000 -type f -print0 2>/dev/null | xargs -0 -r chmod a-s

# Lock system paths. These MUST succeed on a normal Debian/Alpine base
# — any failure here means the image is not properly hardened and the
# build should abort.
chmod 444 /etc/passwd /etc/group
chmod 555 /etc

# Belt-and-suspenders: verify the binaries we tried to remove are
# really gone, in case a future apt+/dpkg+ glob expansion regresses.
for bin in apt apt-get dpkg dpkg-query; do
    if command -v "$bin" >/dev/null 2>&1; then
        echo "[RunSecure] ERROR: $bin still on PATH after finalize-hardening — refusing to produce a degraded image" >&2
        exit 1
    fi
done

# ============================================================================
# H2: optional user-requested tool removal / stubbing
# ============================================================================
# RUNSECURE_HARDENING_REMOVE — comma-separated list of binary names to rm.
# RUNSECURE_HARDENING_STUB   — comma-separated list of binary names to
#                              replace with a friendly stub that explains
#                              why the tool is intentionally unavailable.
#
# Both lists were validated upstream by validate-schema.sh + a sink-side
# guard in compose-image.sh (no shell metachars; alphanumerics and
# hyphens/underscores only). We re-validate here as defense-in-depth —
# any future code path that reaches this script via a different sink
# must still pass the same character-class check.
_h2_validate_name() {
    local name="$1"
    if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        echo "[RunSecure] ERROR: H2 invalid name '$name' — refusing finalize" >&2
        exit 1
    fi
}

# Resolve a name to its absolute path on PATH. Empty if not found.
_h2_locate() {
    command -v "$1" 2>/dev/null || true
}

# H2 stubs: install a tiny POSIX shell script in place of the binary
# that prints why it was removed and exits 127. This is gentler than
# `command not found` for users who deliberately invoked a tool — the
# stub tells them which runner.yml setting hid it.
_h2_install_stub() {
    local name="$1"
    local target
    target=$(_h2_locate "$name")
    if [[ -z "$target" ]]; then
        echo "[RunSecure] H2: '$name' not present on PATH (nothing to stub)" >&2
        return 0
    fi
    rm -f "$target"
    cat > "$target" <<STUB
#!/bin/sh
# RunSecure stub — generated by hardening.stub at image build time.
echo "[runsecure] '$name' was intentionally replaced by hardening.stub in your runner.yml." >&2
echo "[runsecure] If your job needs $name, remove it from hardening.stub or move to hardening.remove + hardening.allow." >&2
exit 127
STUB
    chmod 555 "$target"
    echo "[RunSecure] H2: stubbed $target"
}

_h2_remove_binary() {
    local name="$1"
    local target
    target=$(_h2_locate "$name")
    if [[ -z "$target" ]]; then
        echo "[RunSecure] H2: '$name' not present on PATH (nothing to remove)" >&2
        return 0
    fi
    # Walk every PATH entry once. We track previously seen targets to
    # bound the loop — without this, an rm failure on a system path
    # (e.g. read-only mount) would cause an infinite loop because
    # command -v keeps finding the same file.
    local seen=" "
    while true; do
        local next
        next=$(_h2_locate "$name")
        [[ -z "$next" ]] && break
        case "$seen" in
            *" $next "*)
                echo "[RunSecure] ERROR: H2 cannot remove '$name' at $next (rm failed) — refusing to produce a degraded image" >&2
                exit 1
                ;;
        esac
        seen="${seen}${next} "
        rm -f "$next"
        echo "[RunSecure] H2: removed $next"
    done
}

if [[ -n "${RUNSECURE_HARDENING_REMOVE:-}" ]]; then
    IFS=',' read -ra _h2_rm_list <<<"$RUNSECURE_HARDENING_REMOVE"
    for _name in "${_h2_rm_list[@]}"; do
        [[ -z "$_name" ]] && continue
        _h2_validate_name "$_name"
        _h2_remove_binary "$_name"
    done
fi

if [[ -n "${RUNSECURE_HARDENING_STUB:-}" ]]; then
    IFS=',' read -ra _h2_stub_list <<<"$RUNSECURE_HARDENING_STUB"
    for _name in "${_h2_stub_list[@]}"; do
        [[ -z "$_name" ]] && continue
        _h2_validate_name "$_name"
        _h2_install_stub "$_name"
    done
fi

echo "[RunSecure] Hardening finalized."
