apiVersion: v1
kind: Service
metadata:
  name: {{ include "runsecure-orchestrator.fullname" . }}
  namespace: {{ include "runsecure-orchestrator.namespace" . }}
  labels:
    {{- include "runsecure-orchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "runsecure-orchestrator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: state
      port: {{ .Values.service.statePort }}
      targetPort: state
      protocol: TCP
