package docker

import (
	"context"
	"fmt"
)

// SpawnInputs is the complete parameter set for a per-spawn container stack.
//
// Field names here match what orchestrator/spawn.go passes — keep them
// in sync if either changes.
type SpawnInputs struct {
	Scope, Repo, SpawnID string
	NetworkID            string // pre-created by caller; Spawn attaches containers to it
	EgressNetwork        string // external network the proxy is dual-homed onto
	RunnerImage          string // digest-pinned
	ProxyImage           string // digest-pinned
	SeccompProfilePath   string
	ResourcesMemory      int64 // bytes
	ResourcesNanoCPUs    int64 // 1e9 = 1 CPU
	ResourcesPIDs        int64
	JITConfigB64         string
	EgressVolume         string   // shared named Docker volume carrying per-spawn egress configs
	EgressMountPath      string   // path the egress volume is mounted at inside the proxy
	Labels               []string // additional labels (key=value) merged onto every container
	EnableDNSMasq        bool     // when true, inject ENABLE_DNSMASQ=true into proxy env
}

// Spawn creates and starts a 2-container per-spawn stack: one combined proxy
// (dual-homed on internal + egress network) and one runner (internal only).
// The proxy carries all traffic-shaping roles: squid HTTP proxy, haproxy TCP
// egress, and optionally dnsmasq. The runner reaches the internet only through
// the proxy; it is never attached to the egress network.
//
// Returns map of role → container ID. On any failure, rolls back created
// containers (caller deletes the network).
func Spawn(ctx context.Context, c Client, in SpawnInputs) (map[string]string, error) {
	created := map[string]string{}

	// Defensive rollback: on any error, delete every container we created.
	rollback := func() {
		for _, id := range created {
			_ = c.DeleteContainer(ctx, id, true)
		}
	}

	// Common labels every container in this spawn carries.
	commonLabels := map[string]string{
		"runsecure.scope":    in.Scope,
		"runsecure.repo":     in.Repo,
		"runsecure.spawn_id": in.SpawnID,
	}

	// Common HostConfig fragments.
	hcBase := HostConfig{
		CapDrop:        []string{"ALL"},
		SecurityOpt:    []string{"no-new-privileges:true"},
		NetworkMode:    in.NetworkID,
		ReadonlyRootfs: true,
		AutoRemove:     false,
	}

	// 1. Combined proxy container (dual-homed: internal net + egress net).
	//
	// The egress config files live in a spawn-scoped subdir of the shared
	// named egress volume (written by the orchestrator). The volume is mounted
	// read-only; the proxy reads its config paths from SQUID_CFG / HAPROXY_CFG /
	// DNSMASQ_CFG, which point at <EgressMountPath>/<SpawnID>/<file>.
	spawnDir := in.EgressMountPath + "/" + in.SpawnID
	proxyEnv := []string{
		"ENABLE_HAPROXY=true",
		"SQUID_CFG=" + spawnDir + "/squid.conf",
		"HAPROXY_CFG=" + spawnDir + "/haproxy.cfg",
		"DNSMASQ_CFG=" + spawnDir + "/dnsmasq.conf",
	}
	if in.EnableDNSMasq {
		proxyEnv = append(proxyEnv, "ENABLE_DNSMASQ=true")
	}

	proxyLabels := merge(commonLabels, map[string]string{"runsecure.role": "proxy"})
	proxyHC := hcBase
	// Mount the shared egress volume read-only. Docker accepts a volume name
	// (no leading "/") as a Bind source; the socket-proxy gates this to the
	// designated egress volume on role=proxy only.
	proxyHC.Binds = []string{
		in.EgressVolume + ":" + in.EgressMountPath + ":ro",
	}
	// Tmpfs mounts for the proxy's read-only rootfs. Squid writes a PID file,
	// access log, and cache swap dirs; HAProxy writes a stats socket. These
	// paths must be writable tmpfs — they cannot be on the read-only overlay.
	// The squid.conf generated by egress.RenderSquid() explicitly sets these
	// paths so squid does not fall back to its compiled-in defaults.
	// noexec and nosuid prevent execution of binaries dropped into these dirs
	// and block setuid escalation. nodev ensures no device nodes can be created.
	// None of these flags affect write access, so squid/haproxy can still write
	// PID files, log files, cache swap dirs, and stats sockets as before.
	proxyHC.Tmpfs = map[string]string{
		"/var/run/squid":   "noexec,nosuid,nodev,uid=1001,gid=1001,mode=750",
		"/var/log/squid":   "noexec,nosuid,nodev,uid=1001,gid=1001,mode=750",
		"/var/spool/squid": "noexec,nosuid,nodev,uid=1001,gid=1001,mode=750",
		"/var/lib/haproxy": "noexec,nosuid,nodev,uid=1001,gid=1001,mode=750",
		"/run":             "noexec,nosuid,nodev,uid=1001,gid=1001,mode=750",
		"/tmp":             "noexec,nosuid,nodev,uid=1001,gid=1001,mode=750",
	}

	// The proxy is attached to both the internal network (alias "proxy" so
	// the runner can reach it) and the egress network (for internet access).
	proxyEndpoints := map[string]EndpointConfig{
		in.NetworkID: {Aliases: []string{"proxy"}},
	}
	if in.EgressNetwork != "" {
		proxyEndpoints[in.EgressNetwork] = EndpointConfig{}
	}

	proxyName := fmt.Sprintf("rs-%s-proxy", in.SpawnID)
	proxyID, err := c.CreateContainer(ctx, CreateContainerRequest{
		Name: proxyName, Image: in.ProxyImage, User: "1001:0",
		Env:    proxyEnv,
		Labels: proxyLabels, HostConfig: proxyHC,
		NetworkingConfig: &NetworkingConfig{EndpointsConfig: proxyEndpoints},
	})
	if err != nil {
		rollback()
		return nil, fmt.Errorf("docker: create proxy: %w", err)
	}
	created["proxy"] = proxyID

	// 2. Runner container (internal network only — NEVER attached to EgressNetwork).
	runnerLabels := merge(commonLabels, map[string]string{"runsecure.role": "runner"})
	runnerHC := hcBase
	runnerHC.Memory = in.ResourcesMemory
	runnerHC.NanoCPUs = in.ResourcesNanoCPUs
	runnerHC.PidsLimit = in.ResourcesPIDs
	runnerHC.Tmpfs = map[string]string{"/tmp": "noexec,nosuid,nodev,size=512m"}
	if in.SeccompProfilePath != "" {
		// Don't mutate hcBase's slice; build a fresh one.
		runnerHC.SecurityOpt = append(append([]string{}, hcBase.SecurityOpt...),
			"seccomp="+in.SeccompProfilePath)
	}

	// Runner routes all traffic through the proxy on the internal network.
	runnerEnv := []string{
		"RUNNER_JIT_CONFIG=" + in.JITConfigB64,
		"HTTP_PROXY=http://proxy:3128",
		"HTTPS_PROXY=http://proxy:3128",
		"NO_PROXY=localhost",
	}

	runnerName := fmt.Sprintf("rs-%s-runner", in.SpawnID)
	runnerID, err := c.CreateContainer(ctx, CreateContainerRequest{
		Name: runnerName, Image: in.RunnerImage, User: "1001:0",
		Env:    runnerEnv,
		Labels: runnerLabels, HostConfig: runnerHC,
		NetworkingConfig: &NetworkingConfig{
			EndpointsConfig: map[string]EndpointConfig{
				in.NetworkID: {},
			},
		},
	})
	if err != nil {
		rollback()
		return nil, fmt.Errorf("docker: create runner: %w", err)
	}
	created["runner"] = runnerID

	// Start order: proxy first (must be ready before runner registers with GitHub).
	for _, role := range []string{"proxy", "runner"} {
		if err := c.StartContainer(ctx, created[role]); err != nil {
			rollback()
			return nil, fmt.Errorf("docker: start %s: %w", role, err)
		}
	}
	return created, nil
}

func merge(a, b map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range a {
		out[k] = v
	}
	for k, v := range b {
		out[k] = v
	}
	return out
}
